/// Flutter icons PrinterIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PrinterIcons
///      fonts:
///       - asset: fonts/PrinterIcons.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class PrinterIcons {
  PrinterIcons._();

  static const _kFontFam = 'PrinterIcons';
  static const String? _kFontPkg = null;

  static const IconData hot_surface = IconData(0xea08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
